// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package login is a generated protocol buffer package.

login message optional from 1000-1999

It is generated from these files:
	login.proto

It has these top-level messages:
	CGLogin
	GCLogin
	CGPing
	GCPing
*/
package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pb "game/basic/pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CGLogin struct {
	PlayerId         *int64  `protobuf:"varint,1,req,name=playerId" json:"playerId,omitempty"`
	Token            *string `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGLogin) Reset()                    { *m = CGLogin{} }
func (m *CGLogin) String() string            { return proto.CompactTextString(m) }
func (*CGLogin) ProtoMessage()               {}
func (*CGLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CGLogin) GetPlayerId() int64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *CGLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type GCLogin struct {
	PlayerId         *int64 `protobuf:"varint,1,req,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GCLogin) Reset()                    { *m = GCLogin{} }
func (m *GCLogin) String() string            { return proto.CompactTextString(m) }
func (*GCLogin) ProtoMessage()               {}
func (*GCLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GCLogin) GetPlayerId() int64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type CGPing struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CGPing) Reset()                    { *m = CGPing{} }
func (m *CGPing) String() string            { return proto.CompactTextString(m) }
func (*CGPing) ProtoMessage()               {}
func (*CGPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GCPing struct {
	Now              *int64 `protobuf:"varint,1,req,name=now" json:"now,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GCPing) Reset()                    { *m = GCPing{} }
func (m *GCPing) String() string            { return proto.CompactTextString(m) }
func (*GCPing) ProtoMessage()               {}
func (*GCPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GCPing) GetNow() int64 {
	if m != nil && m.Now != nil {
		return *m.Now
	}
	return 0
}

var E_CgLogin = &proto.ExtensionDesc{
	ExtendedType:  (*pb.Message)(nil),
	ExtensionType: (*CGLogin)(nil),
	Field:         101,
	Name:          "login.cgLogin",
	Tag:           "bytes,101,opt,name=cgLogin",
}

var E_GcLogin = &proto.ExtensionDesc{
	ExtendedType:  (*pb.Message)(nil),
	ExtensionType: (*GCLogin)(nil),
	Field:         102,
	Name:          "login.gcLogin",
	Tag:           "bytes,102,opt,name=gcLogin",
}

var E_CgPing = &proto.ExtensionDesc{
	ExtendedType:  (*pb.Message)(nil),
	ExtensionType: (*CGPing)(nil),
	Field:         103,
	Name:          "login.cgPing",
	Tag:           "bytes,103,opt,name=cgPing",
}

var E_GcPing = &proto.ExtensionDesc{
	ExtendedType:  (*pb.Message)(nil),
	ExtensionType: (*GCPing)(nil),
	Field:         104,
	Name:          "login.gcPing",
	Tag:           "bytes,104,opt,name=gcPing",
}

func init() {
	proto.RegisterType((*CGLogin)(nil), "login.CGLogin")
	proto.RegisterType((*GCLogin)(nil), "login.GCLogin")
	proto.RegisterType((*CGPing)(nil), "login.CGPing")
	proto.RegisterType((*GCPing)(nil), "login.GCPing")
	proto.RegisterExtension(E_CgLogin)
	proto.RegisterExtension(E_GcLogin)
	proto.RegisterExtension(E_CgPing)
	proto.RegisterExtension(E_GcPing)
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x24, 0xd3, 0x13, 0x73,
	0x53, 0xf5, 0x93, 0x12, 0x8b, 0x33, 0x93, 0xf5, 0x0b, 0x92, 0x20, 0x0c, 0x88, 0x0a, 0x25, 0x6b,
	0x2e, 0x76, 0x67, 0x77, 0x1f, 0x90, 0x2a, 0x21, 0x29, 0x2e, 0x8e, 0x82, 0x9c, 0xc4, 0xca, 0xd4,
	0x22, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x26, 0x0d, 0xe6, 0x20, 0x38, 0x5f, 0x48, 0x84, 0x8b, 0xb5,
	0x24, 0x3f, 0x3b, 0x35, 0x4f, 0x82, 0x09, 0x28, 0xc1, 0x19, 0x04, 0xe1, 0x28, 0xa9, 0x72, 0xb1,
	0xbb, 0x3b, 0x13, 0xd4, 0xac, 0xc4, 0xc1, 0xc5, 0xe6, 0xec, 0x1e, 0x90, 0x99, 0x97, 0xae, 0x24,
	0xc5, 0xc5, 0xe6, 0xee, 0x0c, 0x62, 0x09, 0x09, 0x70, 0x31, 0xe7, 0xe5, 0x97, 0x43, 0x95, 0x82,
	0x98, 0x56, 0xa6, 0x5c, 0xec, 0xc9, 0xe9, 0x10, 0xc3, 0xb8, 0xf5, 0x0a, 0x92, 0xf4, 0x7c, 0x53,
	0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x52, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0xf8, 0xf4, 0x20, 0xfe,
	0x82, 0x3a, 0x36, 0x08, 0xa6, 0x16, 0xa4, 0x2d, 0x3d, 0x19, 0x8b, 0xb6, 0x34, 0x14, 0x6d, 0x50,
	0x67, 0x06, 0xc1, 0xd4, 0x5a, 0x19, 0x71, 0xb1, 0x25, 0xa7, 0x83, 0x5d, 0x82, 0xa2, 0x2b, 0x1d,
	0xac, 0x8b, 0x17, 0x6e, 0x19, 0x48, 0x45, 0x10, 0x54, 0x25, 0x48, 0x4f, 0x7a, 0x32, 0xa6, 0x9e,
	0x0c, 0x14, 0x3d, 0x10, 0xff, 0x05, 0x41, 0x55, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x5c,
	0x0d, 0x4b, 0x8f, 0x01, 0x00, 0x00,
}
