// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

common message optional from 201-300

It is generated from these files:
	common.proto

It has these top-level messages:
	GCError
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pb "game/basic/pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GCError struct {
	ErrorCode        *int32 `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GCError) Reset()                    { *m = GCError{} }
func (m *GCError) String() string            { return proto.CompactTextString(m) }
func (*GCError) ProtoMessage()               {}
func (*GCError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GCError) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

var E_GcError = &proto.ExtensionDesc{
	ExtendedType:  (*pb.Message)(nil),
	ExtensionType: (*GCError)(nil),
	Field:         201,
	Name:          "common.gcError",
	Tag:           "bytes,201,opt,name=gcError",
}

func init() {
	proto.RegisterType((*GCError)(nil), "common.GCError")
	proto.RegisterExtension(E_GcError)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0x24, 0xd3, 0x13,
	0x73, 0x53, 0xf5, 0x93, 0x12, 0x8b, 0x33, 0x93, 0xf5, 0x0b, 0x92, 0x20, 0x0c, 0x88, 0x12, 0x25,
	0x75, 0x2e, 0x76, 0x77, 0x67, 0xd7, 0xa2, 0xa2, 0xfc, 0x22, 0x21, 0x19, 0x2e, 0xce, 0x54, 0x10,
	0xc3, 0x39, 0x3f, 0x25, 0x55, 0x82, 0x51, 0x81, 0x49, 0x83, 0x35, 0x08, 0x21, 0x60, 0x65, 0xce,
	0xc5, 0x9e, 0x9e, 0x0c, 0x51, 0xc8, 0xad, 0x57, 0x90, 0xa4, 0xe7, 0x9b, 0x5a, 0x5c, 0x9c, 0x98,
	0x9e, 0x2a, 0x71, 0x92, 0x51, 0x81, 0x51, 0x83, 0xdb, 0x88, 0x5f, 0x0f, 0x6a, 0x33, 0xd4, 0xb4,
	0x20, 0x98, 0x6a, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x50, 0x9d, 0x08, 0x93, 0x00, 0x00,
	0x00,
}
